import re

def replaceContractions(txt):
    txt = re.sub("I'm", "I am", txt, flags=re.IGNORECASE)
    txt = re.sub("There's", "There is", txt, flags=re.IGNORECASE)
    txt = re.sub("there's", "there is", txt, flags=re.IGNORECASE)
    txt = re.sub("it's", "it is", txt, flags=re.IGNORECASE)
    txt = re.sub("'cause","because", txt, flags=re.IGNORECASE)
    txt = re.sub("'twas","it was", txt, flags=re.IGNORECASE)
    txt = re.sub("ain't","am not", txt, flags=re.IGNORECASE)
    txt = re.sub("aren't","are not", txt, flags=re.IGNORECASE)
    txt = re.sub("can't","cannot", txt, flags=re.IGNORECASE)
    txt = re.sub("could've","could have", txt, flags=re.IGNORECASE)
    txt = re.sub("couldn't","could not", txt, flags=re.IGNORECASE)
    txt = re.sub("couldn't've","could have not", txt, flags=re.IGNORECASE)
    txt = re.sub("didn't","did not", txt, flags=re.IGNORECASE)
    txt = re.sub("doesn't","do not", txt, flags=re.IGNORECASE)
    txt = re.sub("don't","do not", txt, flags=re.IGNORECASE)
    txt = re.sub("everybody's","eve'rybody has", txt, flags=re.IGNORECASE)
    txt = re.sub("haven't","have not", txt, flags=re.IGNORECASE)
    txt = re.sub("he'd","he would", txt, flags=re.IGNORECASE)
    txt = re.sub("he'll","he will", txt, flags=re.IGNORECASE)
    txt = re.sub("he's","he is", txt, flags=re.IGNORECASE)
    txt = re.sub("here's","here is", txt, flags=re.IGNORECASE)
    txt = re.sub("how'd","how did", txt, flags=re.IGNORECASE)
    txt = re.sub("how'll","how will", txt, flags=re.IGNORECASE)
    txt = re.sub("how're","how are", txt, flags=re.IGNORECASE)
    txt = re.sub("how's","how is", txt, flags=re.IGNORECASE)
    txt = re.sub("i'am","I am", txt, flags=re.IGNORECASE)
    txt = re.sub("i'd","I had", txt, flags=re.IGNORECASE)
    txt = re.sub("i'll","I will", txt, flags=re.IGNORECASE)
    txt = re.sub("i'm","I am", txt, flags=re.IGNORECASE)
    txt = re.sub("i've","I have", txt, flags=re.IGNORECASE)
    txt = re.sub("i've", "I have", txt, flags=re.IGNORECASE)
    txt = re.sub("isn't","is not", txt, flags=re.IGNORECASE)
    txt = re.sub("it'd","it would", txt, flags=re.IGNORECASE)
    txt = re.sub("it'll","it will", txt, flags=re.IGNORECASE)
    txt = re.sub("it's","it is", txt, flags=re.IGNORECASE)
    txt = re.sub("let's","let us", txt, flags=re.IGNORECASE)
    txt = re.sub("ma'am","madam", txt, flags=re.IGNORECASE)
    txt = re.sub("may've","may have", txt, flags=re.IGNORECASE)
    txt = re.sub("might've","might have", txt, flags=re.IGNORECASE)
    txt = re.sub("mightn't","might not", txt, flags=re.IGNORECASE)
    txt = re.sub("must've","must have", txt, flags=re.IGNORECASE)
    txt = re.sub("mustn't","must not", txt, flags=re.IGNORECASE)
    txt = re.sub("needn't","need not", txt, flags=re.IGNORECASE)
    txt = re.sub("nothing's","nothing is", txt, flags=re.IGNORECASE)
    txt = re.sub("ought'nt","ought not", txt, flags=re.IGNORECASE)
    txt = re.sub("ought've","ought have", txt, flags=re.IGNORECASE)
    txt = re.sub("shan't","shall not", txt, flags=re.IGNORECASE)
    txt = re.sub("she'd","she had", txt, flags=re.IGNORECASE)
    txt = re.sub("she'll","she will", txt, flags=re.IGNORECASE)
    txt = re.sub("she's","she is", txt, flags=re.IGNORECASE)
    txt = re.sub("should've","should have", txt, flags=re.IGNORECASE)
    txt = re.sub("shouldn't","should not", txt, flags=re.IGNORECASE)
    txt = re.sub("somebody's","somebody is", txt, flags=re.IGNORECASE)
    txt = re.sub("someone's","someone is", txt, flags=re.IGNORECASE)
    txt = re.sub("something's","something is", txt, flags=re.IGNORECASE)
    txt = re.sub("that'd","that would", txt, flags=re.IGNORECASE)
    txt = re.sub("that'll","that will", txt, flags=re.IGNORECASE)
    txt = re.sub("that're","that are", txt, flags=re.IGNORECASE)
    txt = re.sub("that's","that is", txt, flags=re.IGNORECASE)
    txt = re.sub("there'd","there had", txt, flags=re.IGNORECASE)
    txt = re.sub("there'll","there will", txt, flags=re.IGNORECASE)
    txt = re.sub("there's","there has", txt, flags=re.IGNORECASE)
    txt = re.sub("these're","these are", txt, flags=re.IGNORECASE)
    txt = re.sub("these've","these have", txt, flags=re.IGNORECASE)
    txt = re.sub("they'd","they had", txt, flags=re.IGNORECASE)
    txt = re.sub("they'll","they will", txt, flags=re.IGNORECASE)
    txt = re.sub("they're","they are", txt, flags=re.IGNORECASE)
    txt = re.sub("they've","they have", txt, flags=re.IGNORECASE)
    txt = re.sub("this's","this is", txt, flags=re.IGNORECASE)
    txt = re.sub("wasn't","was not", txt, flags=re.IGNORECASE)
    txt = re.sub("we'd","we had", txt, flags=re.IGNORECASE)
    txt = re.sub("we'll","we will", txt, flags=re.IGNORECASE)
    txt = re.sub("we're","we are", txt, flags=re.IGNORECASE)
    txt = re.sub("we've","we have", txt, flags=re.IGNORECASE)
    txt = re.sub("weren't","were not", txt, flags=re.IGNORECASE)
    txt = re.sub("what'd","what did", txt, flags=re.IGNORECASE)
    txt = re.sub("what'll","what will", txt, flags=re.IGNORECASE)
    txt = re.sub("what're","what are", txt, flags=re.IGNORECASE)
    txt = re.sub("what's","what is", txt, flags=re.IGNORECASE)
    txt = re.sub("where'd","where did", txt, flags=re.IGNORECASE)
    txt = re.sub("where're","where are", txt, flags=re.IGNORECASE)
    txt = re.sub("where've","where have", txt, flags=re.IGNORECASE)
    txt = re.sub("who'd","who had", txt, flags=re.IGNORECASE)
    txt = re.sub("who'll","who will", txt, flags=re.IGNORECASE)
    txt = re.sub("who's","who is", txt, flags=re.IGNORECASE)
    txt = re.sub("who've","who have", txt, flags=re.IGNORECASE)
    txt = re.sub("why'd","why did", txt, flags=re.IGNORECASE)
    txt = re.sub("why'll","why will", txt, flags=re.IGNORECASE)
    txt = re.sub("why's","why is", txt, flags=re.IGNORECASE)
    txt = re.sub("won't","would not", txt, flags=re.IGNORECASE)
    txt = re.sub("would've","would have", txt, flags=re.IGNORECASE)
    txt = re.sub("wouldn't","would not", txt, flags=re.IGNORECASE)
    txt = re.sub("y'know","you know", txt, flags=re.IGNORECASE)
    txt = re.sub("you'd","you had", txt, flags=re.IGNORECASE)
    txt = re.sub("you'll","you will", txt, flags=re.IGNORECASE)
    txt = re.sub("you're","you are", txt, flags=re.IGNORECASE)
    txt = re.sub("you've","you have", txt, flags=re.IGNORECASE)
    txt = re.sub("new paragraph.","\n \n", txt, flags=re.IGNORECASE)
    return txt

